server.address=0.0.0.0
server.port=8080

# Keep this (no DB yet)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Use IP restricted key
google.api.key=AIzaSyDgoK2GwngbZ8GV8g5WhBDtvovpI9CCw2o